app:
  hosts:
    fasttext: http://0.0.0.0:8079
    pg: postgresql://user:pass@localhost:5434/db
  paths:
    regions: persistant/regions.pickle
    locality: persistant/locality.pickle
    cords: persistant/coords.pickle
    categories: persistant/categories.json
    vacs_test: persistant/struct_actual_vac.pickle
    index_test: persistant/index_cache.p
  constant:
    time_for_sleep_sheduller: 43200


